### ISSUE TITLE
Align the main inputs in one line for better vertical space use

### ISSUE THREAD

**Issue by sabi0** [RESTEDClient/RESTED#79]
Super-long Method drop-down is a waste of space.
I'd suggest to put all the three main controls in one line for a streamlined and more concise UI.

The Method drop-down does not need a label (everyone using RESTED knows what GET / POST is, I believe).
And for the URL the 'http://...' hint is enough (and is more in line with the hint-labels for other controls - Name / Value in Headers, Username / Password)

Check the mockup:
[![mockup.png](https://s30.postimg.org/ppgqtcykx/mockup.png)](https://postimg.org/image/k1ag2gu8d/)

**Comment by esphen** [comment]
Thanks for the suggestion, I'm open to suggestions to improving the UX of the extension. We need to keep design for screen reader users though, so in the mockup above we need to include hidden labels for the fields.

As for the URL, the URL in the placeholder is part an easter egg and part a dev tool. It is very convenient for me to be developing the extension and just press "enter" to get a result instead of having to type a URL all the time. So it will stay, unless someone can provide a very convincing reason for it not to.

**Comment by sabi0** [comment]
> the URL in the placeholder is part an easter egg and part a dev tool

This is actually a good idea for a preference.
I also use the same address most of the time. So it would be nice if it was there right when I open RESTED.

Also 99% of the requests I make are POSTs with some JSON body. (I use browser's address bar for GETs)
So it would be great if there was an option to specify that I want method to be set to POST and body expanded when I open RESTED. That would save me some annoying clicks I have to do every time I open RESTED.

You could probably make the add-on remember the last used "layout" instead of adding extra preferences options.

**Comment by hdwilber** [comment]
Hi, there.
I would like to contribute to solve this issue. These are my screenshots. However, I am not sure how PR are opened for this repository.

### Request fields when `custom` is not selected
![Request fields without selecting `custom`](https://user-images.githubusercontent.com/16395551/38286977-2ff9246e-3796-11e8-88ab-78cb363b48d1.png)
### Request fields when  `custom` is selected
![selection_007](https://user-images.githubusercontent.com/16395551/38286976-2fd04120-3796-11e8-94fc-4d6d8cc21016.png)
